[build]
command = "npm run netlify:prepare-db && npm run build && npm run netlify:bundle-db"

[functions]
included_files = ["prisma/dev.db"]

[[plugins]]
package = "@netlify/plugin-nextjs"

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
